Resolve 12
etases/EduBlock.RS pull request #22
Opened 2022-09-25 11:25 UTC by khoinguyen26

- staff create class

2022-09-25 11:32 UTC, HSGamer requested changes

2022-09-25 11:32 UTC, HSGamer commented on src/main/java/io/github/etases/edublock/rs/model/input/ClassCreate.java
> +    public String getClassName() {
Not needed. `name()` exists.

2022-09-25 11:37 UTC, khoinguyen26 commented on src/main/java/io/github/etases/edublock/rs/model/input/ClassCreate.java
> +    public String getClassName() {
fixed

2022-09-27 02:55 UTC, HSGamer requested changes

2022-09-27 02:55 UTC, HSGamer commented on src/main/java/io/github/etases/edublock/rs/handler/StaffHandler.java
> +                if (session.get(Classroom.class, input.name()) != null) {
Use query
`name` is not primary key

2022-09-27 02:56 UTC, HSGamer requested changes

2022-09-27 02:56 UTC, HSGamer commented on src/main/java/io/github/etases/edublock/rs/handler/StaffHandler.java
> +                }
??

Where is response?

2022-09-27 03:01 UTC, HSGamer requested changes

2022-09-27 03:01 UTC, HSGamer commented on src/main/java/io/github/etases/edublock/rs/handler/StaffHandler.java
> +                    ctx.json(response);
```
ctx.status(400);
response.setStatus(1);
ctx.json(response);
```

2022-09-28 13:17 UTC, merged