18 student view personal record
etases/EduBlock.RS pull request #27
Opened 2022-09-29 12:51 UTC by khoatvbattu

Check lại giúp a :V
Do dùng acc role Admin nên test k được role Student :V

2022-09-29 14:09 UTC, HSGamer requested changes
Muốn lấy mấy cái RecordEntry thì phải lấy từ cái Record chứ nhỉ? Cái id của RecordEntry đâu phải id của Student.

2022-09-29 14:12 UTC, HSGamer commented
Record là nguyên cái học bạ, còn cái RecordEntry chỉ là cho từng môn trong học bạ thôi.

2022-09-30 09:57 UTC, khoatvbattu commented
Review giúp a xem có lỗi gì hong

2022-09-30 09:59 UTC, khoatvbattu commented
Mới fix lại 1 số thứ như: 

- query qua bên Record para là studentId
- sửa lại cái record RecordEntryOutput thành 
        String classroomName,
        String subject,
        float firstHalfScore,
        float secondHalfScore,
        float finalScore

- với cái RecordEntryListResponse thành data ra dạng List

2022-09-30 10:10 UTC, HSGamer requested changes
* Thêm `classroomId` để lọc theo lớp
  `server.get("/recordentry/<classroomId>")`
  `long classroomId = Long.parseLong(ctx.pathParam("classId"))`
* Sửa lại query và sử dụng parameter `student` và `classroomId` để lọc ra theo học sinh và lớp
  `
@NamedQuery(name = "Record.findPersonalRecordEntry", query = "Select r.recordEntry FROM Record r WHERE student.id = :student and classroom.id = :classroomId")`

2022-10-01 07:14 UTC, HSGamer requested changes

2022-10-01 07:14 UTC, HSGamer commented on src/main/java/io/github/etases/edublock/rs/handler/RecordEntryHandler.java
> +                long classroomId = Long.parseLong(ctx.pathParam("classId"));
`ctx.pathParam("classroomId")`

2022-10-01 07:33 UTC, HSGamer approved these changes

2022-10-01 07:33 UTC, merged